#define BIT_0                     0x00000001U
#define BIT_1                     0x00000002U
#define BIT_2                     0x00000004U
#define BIT_3                     0x00000008U
#define BIT_4                     0x00000010U
#define BIT_5                     0x00000020U
#define BIT_6                     0x00000040U
#define BIT_7                     0x00000080U
#define BIT_8                     0x00000100U
#define BIT_9                     0x00000200U
#define BIT_10                    0x00000400U
#define BIT_11                    0x00000800U
#define BIT_12                    0x00001000U
#define BIT_13                    0x00002000U
#define BIT_14                    0x00004000U
#define BIT_15                    0x00008000U
#define BIT_16                    0x00010000U
#define BIT_17                    0x00020000U
#define BIT_18                    0x00040000U
#define BIT_19                    0x00080000U
#define BIT_20                    0x00100000U
#define BIT_21                    0x00200000U
#define BIT_22                    0x00400000U
#define BIT_23                    0x00800000U
#define BIT_24                    0x01000000U
#define BIT_25                    0x02000000U
#define BIT_26                    0x04000000U
#define BIT_27                    0x08000000U
#define BIT_28                    0x10000000U
#define BIT_29                    0x20000000U
#define BIT_30                    0x40000000U
#define BIT_31                    0x80000000U

// EAX=1, ECX
#define INTEL_FF_SSE3             BIT_0
#define INTEL_FF_PCLMULQDQ        BIT_1
#define INTEL_FF_DTEST64          BIT_2
#define INTEL_FF_MONITOR          BIT_3
#define INTEL_FF_DS_CPL           BIT_4
#define INTEL_FF_VMX              BIT_5
#define INTEL_FF_SMX              BIT_6
#define INTEL_FF_EIS              BIT_7
#define INTEL_FF_TM2              BIT_8
#define INTEL_FF_SSSE3            BIT_9
#define INTEL_FF_CNXT_ID          BIT_10
// [11] (reserved)
#define INTEL_FF_FMA              BIT_12
#define INTEL_FF_CX16             BIT_13
#define INTEL_FF_XTPR             BIT_14
#define INTEL_FF_PDCM             BIT_15
// [16] (reserved)
#define INTEL_FF_PCID             BIT_17
#define INTEL_FF_DCA              BIT_18
#define INTEL_FF_SSE4_1           BIT_19
#define INTEL_FF_SSE4_2           BIT_20
#define INTEL_FF_X2APIC           BIT_21
#define INTEL_FF_MOVBE            BIT_22
#define INTEL_FF_POPCNT           BIT_23
#define INTEL_FF_TSC_DEADLINE     BIT_24
#define INTEL_FF_AES              BIT_25
#define INTEL_FF_XSAVE            BIT_26
#define INTEL_FF_OSXSAVE          BIT_27
#define INTEL_FF_AVX              BIT_28
#define INTEL_FF_F16C             BIT_29
#define INTEL_FF_RDRND            BIT_30

// EAX=1, EDX
#define INTEL_FF_FPU              BIT_0
#define INTEL_FF_VME              BIT_1
#define INTEL_FF_DE               BIT_2
#define INTEL_FF_PSE              BIT_3
#define INTEL_FF_TSC              BIT_4
#define INTEL_FF_MSR              BIT_5
#define INTEL_FF_PAE              BIT_6
#define INTEL_FF_MCE              BIT_7
#define INTEL_FF_CX8              BIT_8
#define INTEL_FF_APIC             BIT_9
// [10] (reserved)
#define INTEL_FF_SEP              BIT_11
#define INTEL_FF_MTRR             BIT_12
#define INTEL_FF_PGE              BIT_13
#define INTEL_FF_MCA              BIT_14
#define INTEL_FF_CMOV             BIT_15
#define INTEL_FF_PAT              BIT_16
#define INTEL_FF_PSE_36           BIT_17
#define INTEL_FF_PSN              BIT_18
#define INTEL_FF_CLFSH            BIT_19
// [20] (reserved)
#define INTEL_FF_DS               BIT_21
#define INTEL_FF_ACPI             BIT_22
#define INTEL_FF_MMX              BIT_23
#define INTEL_FF_FXSR             BIT_24
#define INTEL_FF_SSE              BIT_25
#define INTEL_FF_SSE2             BIT_26
#define INTEL_FF_SS               BIT_27
#define INTEL_FF_HTT              BIT_28
#define INTEL_FF_TM               BIT_29
// [30] (reserved)
#define INTEL_FF_PBE              BIT_31

// EAX=0x80000001, ECX
#define INTEL_FF_LAHF_LM          BIT_0
// [31:1] (reserved)

// EAX=0x80000001, EDX
// [10:0] (reserved)
#define INTEL_FF_SYSCALL          BIT_11
// [19:12] (reserved)
#define INTEL_FF_XD_BIT           BIT_20
// [25:21] (reserved)
#define INTEL_FF_PDPE1GB          BIT_26
#define INTEL_FF_RDTSCP           BIT_27
// [28] (reserved)
#define INTEL_FF_INTEL64          BIT_29
// [31:30] (reserved)

// EAX=1, ECX
#define AMD_FF_SSE3               BIT_0
#define AMD_FF_PCLMULQDQ          BIT_1
// [2] (reserved)
#define AMD_FF_MONITOR            BIT_3
// [8:4] (reserved)
#define AMD_FF_SSSE3              BIT_9
// [11:10] (reserved)
#define AMD_FF_FMA                BIT_12
#define AMD_FF_CX16               BIT_13
// [18:14] (reserved)
#define AMD_FF_SSE4_1             BIT_19
#define AMD_FF_SSE4_2             BIT_20
// [22:21] (reserved)
#define AMD_FF_POPCNT             BIT_23
// [24] (reserved)
#define AMD_FF_AES                BIT_25
#define AMD_FF_XSAVE              BIT_26
#define AMD_FF_OSXSAVE            BIT_27
#define AMD_FF_AVX                BIT_28
#define AMD_FF_F16C               BIT_29
// [30] (reserved)
#define AMD_FF_HYPERVISOR         BIT_31

// EAX=1, EDX
#define AMD_FF_FPU                BIT_0
#define AMD_FF_VME                BIT_1
#define AMD_FF_DE                 BIT_2
#define AMD_FF_PSE                BIT_3
#define AMD_FF_TSC                BIT_4
#define AMD_FF_MSR                BIT_5
#define AMD_FF_PAE                BIT_6
#define AMD_FF_MCE                BIT_7
#define AMD_FF_CX8                BIT_8
#define AMD_FF_APIC               BIT_9
// [10] (reserved)
#define AMD_FF_SEP                BIT_11
#define AMD_FF_MTRR               BIT_12
#define AMD_FF_PGE                BIT_13
#define AMD_FF_MCA                BIT_14
#define AMD_FF_CMOV               BIT_15
#define AMD_FF_PAT                BIT_16
#define AMD_FF_PSE_36             BIT_17
// [18] (reserved)
#define AMD_FF_CLFSH              BIT_19
// [22:20] (reserved)
#define AMD_FF_MMX                BIT_23
#define AMD_FF_FXSR               BIT_24
#define AMD_FF_SSE                BIT_25
#define AMD_FF_SSE2               BIT_26
// [27] (reserved)
#define AMD_FF_HTT                BIT_28
// [31:29] (reserved)

// EAX=0x80000001, ECX
#define AMD_FF_LAHF_LM            BIT_0
#define AMD_FF_CMP_LEGACY         BIT_1
#define AMD_FF_SVM                BIT_2
#define AMD_FF_EXTAPIC            BIT_3
#define AMD_FF_CR8_LEGACY         BIT_4
#define AMD_FF_ABM                BIT_5
#define AMD_FF_SSE4A              BIT_6
#define AMD_FF_MISALIGNSSE        BIT_7
#define AMD_FF_3DNOWPREFETCH      BIT_8
#define AMD_FF_OSVW               BIT_9
#define AMD_FF_IBS                BIT_10
#define AMD_FF_XOP                BIT_11
#define AMD_FF_SKINIT             BIT_12
#define AMD_FF_WDT                BIT_13
// [14] (reserved)
#define AMD_FF_LWP                BIT_15
#define AMD_FF_FMA4               BIT_16
// [18:17] (reserved)
#define AMD_FF_NODEID_MSR         BIT_19
// [20] (reserved)
#define AMD_FF_TBM                BIT_21
#define AMD_FF_TOPOEXT            BIT_22
// [31:23] (reserved)

// EAX=0x80000001, EDX
// [17:0] (EAX=1, EDX)
// [19:18] (reserved)
#define AMD_FF_NX                 BIT_20
// [21] (reserved)
#define AMD_FF_MMXEXT             BIT_22
// [24:23] (EAX=1, EDX)
#define AMD_FF_FFXSR              BIT_25
#define AMD_FF_PDPE1GB            BIT_26
#define AMD_FF_RDTSCP             BIT_27
// [28] (reserved)
#define AMD_FF_LM                 BIT_29
#define AMD_FF_3DNOWEXT           BIT_30
#define AMD_FF_3DNOW              BIT_31
